# this file is to bootstrap your initial RancherOS install with minimal modifications required

hostname: k8s0? # https://rancher.com/docs/os/v1.x/en/installation/configuration/hostname/

ssh_authorized_keys: # https://rancher.com/docs/os/v1.x/en/installation/configuration/ssh-keys/
- <public key>

rancher:
  network: # https://rancher.com/docs/os/v1.x/en/installation/networking/
    interfaces: # https://rancher.com/docs/os/v1.x/en/installation/networking/interfaces/
      eth*:
        dhcp: false
      eth0:
        address: 10.0.0.?/24
        gateway: 10.0.0.1
    dns: # https://rancher.com/docs/os/v1.x/en/installation/networking/dns/
      nameservers:
      - 208.67.222.222
      - 208.67.220.220
  services_include: # https://rancher.com/docs/os/v1.x/en/installation/system-services/adding-system-services/
    open-vm-tools: true

write_files: # https://rancher.com/docs/os/v1.x/en/installation/configuration/write-files/#writing-files-in-specific-system-services
- container: ntp
  path: /etc/ntp.conf
  permissions: "0644"
  owner: root
  content: |
    server 0.pool.ntp.org iburst
    server 1.pool.ntp.org iburst
    server 2.pool.ntp.org iburst
    server 3.pool.ntp.org iburst
    
    # Allow only time queries, at a limited rate, sending KoD when in excess.
    # Allow all local queries (IPv4, IPv6)
    restrict default nomodify nopeer noquery limited kod
    restrict 127.0.0.1
    restrict [::1]
      
runcmd: # https://rancher.com/docs/os/v1.x/en/installation/configuration/running-commands/
# Add needed local dns entry
- grep -qxF '10.0.0.90 rancher' /etc/hosts || echo '10.0.0.90 rancher' >> /etc/hosts
# Rancher RKE
# https://rancher.com/docs/rke/latest/en/installation/#download-the-rke-binary
- wget -O /usr/bin/rke https://github.com/rancher/rke/releases/latest/download/rke_linux-amd64 && chmod +x /usr/bin/rke
# CURL
# https://thomasmodeneis.wordpress.com/2017/06/23/installing-curl-on-rancheros/
#- echo 'docker run --rm radial/busyboxplus:curl curl $@' > /usr/bin/curl && chmod +x /usr/bin/curl
# Helm
# https://helm.sh/docs/intro/install/
#- wget -P /tmp https://get.helm.sh/helm-`wget https://github.com/helm/helm/releases -O - 2>&1 | grep 'href="/helm/helm/releases/tag/v3.' | grep -v no-underline | head -n 1 | cut -d '"' -f 2 | awk '{n=split($NF,a,"/");print a[n]}' | awk 'a !~ $0{print}; {a=$0}'`-linux-amd64.tar.gz
- wget -P /tmp https://get.helm.sh/helm-`wget https://api.github.com/repos/helm/helm/releases/latest -O - | jq '.tag_name' -r`-linux-amd64.tar.gz
- gunzip /tmp/helm-* && tar -xf /tmp/helm-*.tar -C /tmp && mv /tmp/linux-amd64/helm /usr/bin/helm
# Kubernetes
# https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-on-linux
- wget -O /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/`wget -O - https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
- chmod +x /usr/bin/kubectl
