version: '3'

services:

  transmission:
    image: linuxserver/transmission
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
     - /mnt/nas/docker/download_automation/transmission/config:/config
     - /mnt/nas/docker/download_automation/transmission/watch:/watch
     - /mnt/nas/docker/download_automation/downloads:/downloads
    deploy:
      replicas: 1
      placement:
        constraints: [node.role != manager]
    environment:
      - PUID=1003 
      - PGID=1100
      - TZ="America/Chicago"
      
  sonarr:
    image: linuxserver/sonarr
    ports:
      - "8989:8989"
    volumes:
     - /mnt/nas/docker/download_automation/sonarr/config:/config
     - /mnt/nas/docker/download_automation/sonarr/tv:/tv
     - /mnt/nas/docker/download_automation/downloads:/downloads
    deploy:
      replicas: 1
      placement:
        constraints: [node.role != manager]
    environment:
      - PUID=1003 
      - PGID=1100
      - TZ="America/Chicago"

  flexget:
    image: cpoppema/docker-flexget
    ports:
      - "5050:5050"
    volumes:
      - /mnt/nas/docker/download_automation/sonarr/config:/config
      - /mnt/nas/docker/download_automation/downloads:/downloads
    deploy:
      replicas: 1
      placement:
        constraints: [node.role != manager]
    environment:
      - PUID=1003 
      - PGID=1100
      - TZ="America/Chicago"
      - WEB_PASSWD=
  
    
